author:
  name: Rodrigo Cortez
  role: Data Scientist 
  bio:  Graduate in Information Technology in Sciences (UNAM). I work at the intersection of science and humanities, focusing on data science, AI, music technology, and interdisciplinary research. Experienced in machine learning, statistical analysis, and data visualization.
  location: Ciudad de MÃ©xico

social:
  - id: "github"
    label: "GitHub"
    href: "https://github.com/roicort"
  - id: "opeprocessing"
    label: "OpenProcessing"
    href: "https://openprocessing.org/user/233138"
  - id: "email"
    label: "Email"
    href: "mailto:rodrigo.cortez@example.com"